// ng serve --open --live-reload false
export const environment = {
    env: "local",
    production: false,
    protocol: "https",
    // protocol: "http",
    hostLocal : "localhost:4200",
    host : {
      // ovnMain : "localhost:8443/",
      // ovnADM  : "localhost:8444/",
      // ovnMNG  : "localhost:8486/",
      // ovnCOD  : "localhost:8488/",
      ovnMain : "app.codesociety.site/",
      ovnADM  : "app.codesociety.site/",
      ovnMNG  : "app.codesociety.site/",
      ovnCOD  : "app.codesociety.site/",
    },
    hostType : 2,
    hostBefore : "", 
    hostAfter : "", 
    firebase_coleccion_base : "OVN_DESA",
    rest: "", 
    service : "",
    firebase: {
      apiKey: "AIzaSyDSaO4789Zco5fy-wd4VrgAsYcMalNfKMM",
      authDomain: "stone-net-265023.firebaseapp.com",
      databaseURL: "https://stone-net-265023.firebaseio.com",
      projectId: "stone-net-265023",
      storageBucket: "stone-net-265023.appspot.com",
      messagingSenderId: "706486790340",
      appId: "1:706486790340:web:f489c27ee05b67138fc191",
      measurementId: "G-Y1PN9XVFXR"
    },
    version : "1.0.0",
    systemId : 98,
    mainModuleFree : true,
    default_languaje: "es",
    oauth_clientid : "API_APM_INLANDNET",
    oauth_secret : "33caa750333af31d49d39e9251ecb592"
};